# Welcome to Jekyll!
title: Liliflower Art - by Lilia Padilla Rivera
email: your-email@example.com
description: Official website for artist Lilia Padilla Rivera
keywords: art,painting,colorpainting,lilia,liliflower,blueliliflower
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
promo: http://liliflowerart.com/assets/images/liliflowerart-promo.jpg
author:
  name: Lilia Padilla Rivera
  twitter: liliflowerart
  role: designer/developer
markdown: kramdown
fonts:
  - "Lato:400,900,700,500,300,100:latin"
sass:
    style: compressed
    sass_dir: assets/css
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
  envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
# Build settings
# theme: minima
# plugins:
#   - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
